### PR TITLE
Updated DX11 Offset for patch 5.58

### PR DESCRIPTION
**Pull request by 4i7**

### CODE REVIEW

**Comment by Raisler84** [comment]
Is there a way to get the steps on how to update this? I had no issues until this latest patch release.

**Comment by AlexisBliss** [comment]
hey could i also get the updated link please as i didnt have an issue last update but now i cant seem to update it kind regards ty

**Comment by TheOGKnight** [comment]
I'm having an issue with this too. Any fix for this right now?

**Comment by Tormentedd** [comment]
just an fyi the address changed to 1DB7F70, I went ahead and changed it. Thank you for trying to help out

(edit) wait the change to the address was correct on the merge request sorry about saying it wasn't. Some how everything else went through fine just not the address change, sorry and thank you I'll try to keep an eye out and see if that happens again

**Comment by FSunkist** [comment]
Hey,
I don't know if this is the right place to state my issue, yet I couldn't find anywhere else.
I used to not have any problems with the updates, yet this update didn't go through with me. Zoomhack app isn't updating at all with the new Offsets.xml
Is there something that I'm doing wrong? knowing that I used to update it with each patch without any problems. Thank you so much for the great work!
Discord: FioraSunkist#1580

**Comment by Tormentedd** [comment]
have you checked if the offsets in the settings file changed in your AppData\Roaming\FFXIVZoomHack folder? if it hasn't you can change them manually

**Comment by Tormentedd** [comment]
Capture

**Comment by FSunkist** [comment]
Thank you for replying!
I made sure that the settings file has changed as well to the recent offsets, yet it still says "No New Update Found"
Pic

**Comment by FSunkist** [comment]
I even tried with the Default URL, and still the same :(

**Comment by Tormentedd** [comment]
its because the date is the same, just change the 1DBFF70 to 1DB7F70 and you will be good to go

**Comment by Tormentedd** [comment]
you can open with notepad and edit there

**Comment by FSunkist** [comment]
IT WORKED T___T!!
You're the best! ty! <3

**Comment by Tormentedd** [comment]
glad to help! enjoy.

**Comment by FSunkist** [comment]
Thanks!

**Comment by Raisler84** [comment]
Thank! This also worked for me as well. So glad to have the better zoom again.

**Pull request merged**
