### PR TITLE
Ultimate Update for zoomhack

### PR DESCRIPTION
**Pull request by kingsznhone**
### 1. Upgrade .NET Framework to 4.8
I advice to migrate to .NET 6 someday. 

Because .NET 6 could pack all the dll into one single exe

### 2.Replace XML to JSON on S&L .

Generate lot's of reference dll (20+) in build folder. that's annoy.

### 3. Replace Memory class with my own MemoryReaderAPI DLL.
[https://github.com/kingsznhone/XIV-Dev-Platform/tree/master/MemoryReader](url)

### 4. Using reverse engineering to automatically find offsets.

Never need to find offsets of new game version with CE. Until the end of the world.

### 5. Some performance optimization.
...

### CODE REVIEW

**Comment by Tormentedd** [comment]
As I try to just make sure the offsets are updated and help ppl out when things go sideways on them with zoomout this is something Jay would have to approve and with him not being as active as he once was it might be a few before you get an answer. I hope with this major of an overhaul you have a running and tested version? Sadly real life has been super busy for me and tbh I just don't have the time to go through this, but if it works as well as you say I hope Jay does.

**Comment by jayotterbein** [comment]
I'll take a look at this, I expect somewhere in the next month or so. I'm currently without a computer, and I don't feel right merging something I can't run.

**Comment by kingsznhone** [comment]
I use those code from patch 4.0 untill now. It work perfect.
Put the fresh compiled exe on my server. Feel free to test it .
[zangai.family/download/ZoomHackUltimate.zip](url)

**Comment by someONEgood** [comment]
To add to this, be it @kingsznhone or @jayotterbein I was wondering if it would be possible to add a horizontal position adjust as well?  Something that would allow for more of a 3rd person view like what you can manage with gpose positioning. But for actual gameplay:

ffxiv_dx11 2022-01-28 18-17-16

**Comment by kingsznhone** [comment]
> To add to this, be it @kingsznhone or @jayotterbein I was wondering if it would be possible to add a horizontal position adjust as well? Something that would allow for more of a 3rd person view like what you can manage with gpose positioning. But for actual gameplay:
> 
> ffxiv_dx11 2022-01-28 18-17-16

I've never dig in 3rd person view control. But I will keep it in my mind.  Maybe sometimes I'll take a look at advanced camera control

**Comment by someONEgood** [comment]
> I've never dig in 3rd person view control. But I will keep it in my mind. Maybe sometimes I'll take a look at advanced camera control

That would be great, I'd really appreciate it. Thank you for the response!

**Comment by jayotterbein** [comment]
The process memory api dll isn't included anywhere, there is no nuget reference for it, and even your github doesn't offer a d/l for it. I can't merge this without running it.

**Comment by kingsznhone** [comment]
> The process memory api dll isn't included anywhere, there is no nuget reference for it, and even your github doesn't offer a d/l for it. I can't merge this without running it.

The lack of nuget reference is kind of wired problem that I can't understand what github action were doing.

**packages\System.Text.Json.6.0.1\build\System.Text.Json.targets**
It is exist in Visual Studio nuget manager, published by microsoft.

For ProcessMemoryAPI.dll , It's  [Here](https://github.com/kingsznhone/XIV-Dev-Platform/tree/master/MemoryReader)

Well then, I upload a release [Here](https://github.com/kingsznhone/FFXIV-Zoom-Hack/releases/tag/v1.0)

If something still went wrong. Clone my master branch to local. compile by manual

**Comment by kingsznhone** [comment]
And I rewrite load and save for setting few minutes ago.  
`Lazy<T>` is no sence. Make codes more complicated.

**Comment by jayotterbein** [comment]
merged manually

**Pull request closed without merging**
